#!/usr/bin/env python3
"""Generate / verify the project NOTICE.

WHY this script exists
----------------------
Microsoft CELA's third-party-notices process requires a per-component
attribution document (`NOTICE`) covering every open-source dependency
distributed with the project (the runtime deps of `apm-cli`). Maintaining
that file by hand drifts the moment anyone bumps a version: the version
string, the copyright snippet, and even the *license text* can change
when an upstream re-licenses or re-authors. Drift means we ship stale or
incorrect attribution -- a real legal/compliance risk.

The generator combines two trusted inputs:

  1. `pyproject.toml` `[project] dependencies` -- the *direct* runtime
     deps. Industry-standard NOTICE scope: transitive deps inherit
     attribution via their parents and are typically covered by their
     own NOTICE files (or are build-only, like `setuptools`/`wheel`,
     which we explicitly exclude in the preamble).

  2. `scripts/notice-metadata.yaml` -- curated overrides authored by a
     human reviewer the first time a dep is added. Holds the SPDX
     identifier, upstream URL, copyright snippet, optional notes, and
     verbatim "additional attribution" text (e.g. the Apache-2.0 NOTICE
     that `requests` ships, or an `AUTHORS` file). PyPI metadata is
     unreliable for these fields (some packages mis-declare their
     license, others omit homepage, snippets need legal review), so the
     YAML is the human-authored source of truth.

License *text* (the verbatim block) is read at runtime from the
installed `*.dist-info/licenses/LICENSE*` files (PEP 639, Python
3.10+ wheels) -- with fall-backs for older wheel layouts. This keeps
the file synchronised with whatever is actually installed in the uv
lockfile, so a `requests` minor bump that ships an updated LICENSE
will get picked up by `--check` automatically.

SBOM is intentionally NOT generated by this script. GitHub's dependency
graph already produces an SPDX SBOM for the repo on demand (Settings >
Security > Software bill of materials, or via the REST API at
GET /repos/{owner}/{repo}/dependency-graph/sbom). Adding a second SBOM
generator here would duplicate that surface without adding value.

Modes
-----
  default  : regenerate NOTICE (overwrite on disk).
  --check  : regenerate to memory, compare to NOTICE on disk, exit 1
             with a unified diff to stderr if they differ. Used by
             .github/workflows/notice-drift.yml.

Exit codes
----------
  0  file written, or --check passed.
  1  --check mode: drift detected (diff printed to stderr).
  2  any error (missing metadata, dep not installed, malformed YAML).
"""

from __future__ import annotations

import argparse
import difflib
import importlib.metadata as ilmd
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

# tomllib is stdlib in 3.11+; this script requires Python 3.10+ runtime
# but pyproject.toml parsing only needs to work on the developer / CI
# machine (3.12 per pyproject.toml). On 3.10 we fall back to `tomli`.
try:
    import tomllib  # type: ignore[import-not-found]
except ModuleNotFoundError:  # pragma: no cover -- 3.10 path
    import tomli as tomllib  # type: ignore[no-redef]

from ruamel.yaml import YAML

REPO_ROOT = Path(__file__).resolve().parent.parent
PYPROJECT = REPO_ROOT / "pyproject.toml"
METADATA_YAML = REPO_ROOT / "scripts" / "notice-metadata.yaml"
NOTICE_OUT = REPO_ROOT / "NOTICE"

# Header that prefixes every NOTICE file. The explanatory paragraph is in
# the YAML (`_header.preamble`) so legal-review of wording lives next
# to the per-component data, not in code.
_FIXED_TOP = (
    "NOTICES\n"
    "\n"
    "This repository incorporates material as listed below or described in the code.\n"
    "\n"
    "---\n"
    "\n"
)


# ---------------------------------------------------------------------------
# Data shapes
# ---------------------------------------------------------------------------

@dataclass
class DepSpec:
    """A single entry parsed from `[project] dependencies`.

    `raw_specifier` preserves everything after the package name -- including
    PEP 508 environment markers (e.g. `; python_version<'3.11'`). We keep
    it verbatim because the NOTICE "Version requirement" line is meant
    to communicate *intent* (what the project asks for), not the resolved
    version (which lives in `uv.lock` / GitHub's dependency graph).
    """

    name: str
    raw_specifier: str  # e.g. ">=8.0.0" or ">=1.2.0; python_version<'3.11'"


@dataclass
class ComponentMeta:
    """Curated per-component data loaded from notice-metadata.yaml."""

    name: str  # canonical/display name as it appears in NOTICE
    pyproject_name: str  # exact name used in pyproject.toml deps
    upstream: str
    spdx: str
    copyright_snippet: str
    notes: str | None = None
    additional_attribution: dict | None = None  # {"source": str, "text": str}
    license_text_override: str | None = None  # used when dist-info unavailable
    # Optional verbatim override for the "Version requirement" cell. Use when
    # the pyproject specifier needs an annotation (e.g. PyYAML is declared as
    # `pyyaml` lower-case but distributed as `PyYAML`, and we want that
    # surfaced in the NOTICE alongside the version).
    version_requirement_override: str | None = None


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------

# PEP 508 dep spec splitter: name is up to the first non-name char. We only
# need name + everything-after; pip / uv have already validated specifiers.
_NAME_BOUNDARY = re.compile(r"^([A-Za-z0-9_.\-]+)(.*)$")


def parse_dependencies(pyproject_path: Path) -> list[DepSpec]:
    data = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))
    raw_deps = data.get("project", {}).get("dependencies", [])
    out: list[DepSpec] = []
    for entry in raw_deps:
        m = _NAME_BOUNDARY.match(entry.strip())
        if not m:
            raise SystemExit(f"error: cannot parse dependency '{entry}'")
        out.append(DepSpec(name=m.group(1), raw_specifier=m.group(2).strip()))
    return out


@dataclass(frozen=True)
class ThirdPartySubmissions:
    preamble: str
    contributors: list[dict]  # [{github: str, prs: [int, ...]}, ...]


def load_metadata(
    yaml_path: Path,
) -> tuple[str, dict[str, ComponentMeta], ThirdPartySubmissions | None]:
    """Return (preamble, name->ComponentMeta map, third-party submissions block)."""
    yaml = YAML(typ="rt")
    data = yaml.load(yaml_path.read_text(encoding="utf-8"))
    preamble = str(data["_header"]["preamble"]).rstrip("\n")
    out: dict[str, ComponentMeta] = {}
    for raw in data["components"]:
        out[str(raw["pyproject_name"])] = ComponentMeta(
            name=str(raw["name"]),
            pyproject_name=str(raw["pyproject_name"]),
            upstream=str(raw["upstream"]),
            spdx=str(raw["spdx"]),
            copyright_snippet=str(raw["copyright_snippet"]),
            notes=str(raw["notes"]) if raw.get("notes") is not None else None,
            additional_attribution=(
                {
                    "source": str(raw["additional_attribution"]["source"]),
                    "text": str(raw["additional_attribution"]["text"]).rstrip("\n"),
                }
                if raw.get("additional_attribution")
                else None
            ),
            license_text_override=(
                str(raw["license_text"]).rstrip("\n")
                if raw.get("license_text") is not None
                else None
            ),
            version_requirement_override=(
                str(raw["version_requirement"])
                if raw.get("version_requirement") is not None
                else None
            ),
        )
    raw_tps = data.get("_third_party_submissions")
    tps: ThirdPartySubmissions | None = None
    if raw_tps is not None:
        tps = ThirdPartySubmissions(
            preamble=str(raw_tps["preamble"]).rstrip("\n"),
            contributors=[
                {
                    "github": str(c["github"]),
                    "prs": [int(n) for n in c.get("prs", [])],
                }
                for c in raw_tps.get("contributors", [])
            ],
        )
    return preamble, out, tps


# ---------------------------------------------------------------------------
# License-text discovery
# ---------------------------------------------------------------------------

# Match the *filename* (not full path) of a plausible license file inside a
# dist-info. Order matters at the call site -- we prefer the PEP 639
# `licenses/` subdirectory layout because that's what modern (>=3.10) wheels
# emit; we then accept the legacy top-level layout, and finally the British
# spelling (`LICENCE`) used by tomli among others.
_LICENSE_FILENAME = re.compile(
    r"^(LICENSE|LICENCE|COPYING|NOTICE)(\.[A-Za-z0-9]+)?$"
)


def _is_license_file(rel_path: str) -> bool:
    fname = rel_path.rsplit("/", 1)[-1]
    if not _LICENSE_FILENAME.match(fname):
        return False
    # Don't pick up upstream NOTICE files as the *license* (those go in
    # `additional_attribution`); we only want the actual license body here.
    if fname.upper().startswith("NOTICE"):
        return False
    # Skip AUTHORS-style files even if PEP 639 stuffed them under licenses/
    # (gitpython does this).
    if "AUTHOR" in fname.upper():
        return False
    return True


def read_installed_license(pyproject_name: str) -> str | None:
    """Return the verbatim license text from the package's dist-info, or None.

    Tries PEP 639 layout first (`<dist-info>/licenses/LICENSE*`), then the
    legacy `<dist-info>/LICENSE*`, and finally `<dist-info>/LICENCE*`. If
    the package is not installed or has no license file in the dist-info,
    returns None and the caller decides what to do (typically: fall back to
    the YAML override, or fail).
    """
    try:
        dist = ilmd.distribution(pyproject_name)
    except ilmd.PackageNotFoundError:
        return None
    files = dist.files or []
    # Bucket by layout preference: PEP 639 wins, then legacy, then anything.
    pep639: list = []
    legacy: list = []
    for f in files:
        s = str(f)
        if not _is_license_file(s):
            continue
        if "/licenses/" in s.replace("\\", "/"):
            pep639.append(f)
        else:
            legacy.append(f)
    chosen = (pep639 or legacy)
    if not chosen:
        return None
    # Prefer LICENSE over COPYING when both are present.
    chosen.sort(key=lambda f: (0 if "LICEN" in str(f).upper() else 1, str(f)))
    raw = chosen[0].read_text(encoding="utf-8")
    # Some upstreams (requests, watchdog ship Apache-2.0) prefix their LICENSE
    # file with a leading blank line. The CELA template doesn't want padding
    # *inside* the fenced code block, so we strip leading/trailing newlines.
    return raw.strip("\n")


# ---------------------------------------------------------------------------
# Renderer
# ---------------------------------------------------------------------------

def render_component(dep: DepSpec, meta: ComponentMeta, license_text: str) -> str:
    parts: list[str] = []
    parts.append(f"## Component. {meta.name}\n\n")
    version_req = meta.version_requirement_override or dep.raw_specifier
    parts.append(f"- Version requirement: `{version_req}`\n")
    parts.append(f"- Upstream: {meta.upstream}\n")
    parts.append(f"- SPDX: `{meta.spdx}`\n")
    if meta.notes:
        parts.append(f"- Notes: {meta.notes}\n")
    parts.append("\n### Open Source License/Copyright Notice.\n\n")
    parts.append(f"_{meta.copyright_snippet}_\n\n")
    parts.append("```\n")
    parts.append(license_text)
    parts.append("\n```\n")
    if meta.additional_attribution:
        src = meta.additional_attribution["source"]
        txt = meta.additional_attribution["text"]
        parts.append(f"\n### Additional Attribution. ({src}, verbatim)\n\n")
        parts.append("```\n")
        parts.append(txt)
        parts.append("\n```\n")
    parts.append("\n---\n")
    return "".join(parts)


def _normalize(name: str) -> str:
    """PEP 503 name normalization: lowercase, [-_.] -> '-'."""
    return re.sub(r"[-_.]+", "-", name).lower()


def render_third_party_submissions(tps: ThirdPartySubmissions) -> str:
    # Each component already ends with `---\n\n` (see render_component +
    # the trailing blank line in render_notice), so we do NOT emit a
    # leading separator here -- doing so would produce two consecutive
    # `---` lines in the file.
    lines = [
        "Submitted on behalf of a third-party\n",
        "\n",
        tps.preamble,
        "\n\n",
    ]
    for entry in tps.contributors:
        prs = ", ".join(f"#{n}" for n in entry["prs"])
        suffix = f" (PRs: {prs})" if prs else ""
        lines.append(f"Submitted on behalf of a third-party: @{entry['github']}{suffix}\n")
    lines.append("\n")
    return "".join(lines)


def render_notice(
    deps: list[DepSpec],
    preamble: str,
    metas: dict[str, ComponentMeta],
    tps: ThirdPartySubmissions | None = None,
) -> str:
    norm_metas = {_normalize(k): v for k, v in metas.items()}
    out: list[str] = [_FIXED_TOP, preamble, "\n\n---\n\n"]
    for dep in deps:
        meta = norm_metas.get(_normalize(dep.name))
        if meta is None:
            raise SystemExit(
                f"error: dependency '{dep.name}' has no entry in "
                f"{METADATA_YAML.relative_to(REPO_ROOT)}. Add a curated "
                f"metadata block (upstream, SPDX, copyright_snippet) and "
                f"re-run."
            )
        license_text = read_installed_license(meta.pyproject_name)
        if license_text is None:
            license_text = meta.license_text_override
        if license_text is None:
            raise SystemExit(
                f"error: cannot locate LICENSE text for '{dep.name}'. "
                f"Either install the package into the active environment "
                f"(uv sync) so it can be read from dist-info, or add a "
                f"`license_text:` literal block override to its entry in "
                f"{METADATA_YAML.relative_to(REPO_ROOT)}."
            )
        out.append(render_component(dep, meta, license_text))
        # Trailing blank line between components (and after the last one)
        # to match the CELA template -- the file ends `---\n\n`.
        out.append("\n")
    if tps is not None and tps.contributors:
        out.append(render_third_party_submissions(tps))
    return "".join(out)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Regenerate or validate NOTICE for apm-cli.",
    )
    p.add_argument(
        "--check",
        action="store_true",
        help="Do not write; exit 1 with unified diff if NOTICE is stale.",
    )
    args = p.parse_args(argv)

    try:
        deps = parse_dependencies(PYPROJECT)
        preamble, metas, tps = load_metadata(METADATA_YAML)
        rendered = render_notice(deps, preamble, metas, tps)
    except SystemExit:
        raise
    except Exception as e:  # pragma: no cover -- defensive
        print(f"error: {e}", file=sys.stderr)
        return 2

    if args.check:
        on_disk = NOTICE_OUT.read_text(encoding="utf-8") if NOTICE_OUT.exists() else ""
        if on_disk == rendered:
            return 0
        diff = difflib.unified_diff(
            on_disk.splitlines(keepends=True),
            rendered.splitlines(keepends=True),
            fromfile=str(NOTICE_OUT.relative_to(REPO_ROOT)) + " (on disk)",
            tofile=str(NOTICE_OUT.relative_to(REPO_ROOT)) + " (regenerated)",
        )
        sys.stderr.write(
            "NOTICE is out of date with pyproject.toml + notice-metadata.yaml.\n"
            "Run `make notice` (or `python scripts/generate-notice.py`) and commit.\n\n"
        )
        sys.stderr.writelines(diff)
        return 1

    NOTICE_OUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
