"""Unit tests for GeminiFormatter -- GEMINI.md stub generation."""

from pathlib import Path

import pytest  # noqa: F401

from apm_cli.compilation.constants import BUILD_ID_PLACEHOLDER
from apm_cli.compilation.gemini_formatter import (
    GeminiCompilationResult,
    GeminiFormatter,
    GeminiPlacement,
)
from apm_cli.primitives.models import PrimitiveCollection
from apm_cli.version import get_version


class TestGeminiFormatterInit:
    """Tests for GeminiFormatter initialization."""

    def test_init_with_valid_directory(self, tmp_path: Path) -> None:
        """Test initialization with a valid directory path."""
        formatter = GeminiFormatter(str(tmp_path))
        assert formatter.base_dir == tmp_path
        assert formatter.warnings == []
        assert formatter.errors == []

    def test_init_with_default_directory(self) -> None:
        """Test initialization with default current directory."""
        formatter = GeminiFormatter()
        assert formatter.base_dir.exists()


class TestGeminiFormatterFormatDistributed:
    """Tests for format_distributed() stub generation."""

    def test_returns_successful_result(self, tmp_path: Path) -> None:
        """format_distributed returns a successful result with one placement."""
        formatter = GeminiFormatter(str(tmp_path))
        primitives = PrimitiveCollection()

        result = formatter.format_distributed(primitives)

        assert isinstance(result, GeminiCompilationResult)
        assert result.success is True
        assert len(result.placements) == 1
        assert len(result.content_map) == 1
        assert result.errors == []

    def test_placement_points_to_gemini_md(self, tmp_path: Path) -> None:
        """The single placement should target GEMINI.md at the project root."""
        formatter = GeminiFormatter(str(tmp_path))
        result = formatter.format_distributed(PrimitiveCollection())

        placement = result.placements[0]
        assert isinstance(placement, GeminiPlacement)
        assert placement.gemini_path == tmp_path / "GEMINI.md"

    def test_stub_contains_agents_import(self, tmp_path: Path) -> None:
        """The generated stub must contain the @./AGENTS.md import."""
        formatter = GeminiFormatter(str(tmp_path))
        result = formatter.format_distributed(PrimitiveCollection())

        content = list(result.content_map.values())[0]  # noqa: RUF015
        assert "@./AGENTS.md" in content

    def test_stub_contains_header_and_version(self, tmp_path: Path) -> None:
        """The stub should contain the APM header, build ID, and version."""
        formatter = GeminiFormatter(str(tmp_path))
        result = formatter.format_distributed(PrimitiveCollection())

        content = list(result.content_map.values())[0]  # noqa: RUF015
        assert "# GEMINI.md" in content
        assert "Generated by APM CLI" in content
        assert BUILD_ID_PLACEHOLDER in content
        assert get_version() in content

    def test_stats_reflect_primitives_count(self, tmp_path: Path) -> None:
        """Stats should include the primitive count from the collection."""
        formatter = GeminiFormatter(str(tmp_path))
        result = formatter.format_distributed(PrimitiveCollection())

        assert result.stats["gemini_files_generated"] == 1
        assert "primitives_found" in result.stats

    def test_placement_map_is_ignored(self, tmp_path: Path) -> None:
        """placement_map is accepted for interface compat but not used."""
        formatter = GeminiFormatter(str(tmp_path))
        fake_map = {Path("some/dir"): []}

        result = formatter.format_distributed(PrimitiveCollection(), placement_map=fake_map)

        assert result.success is True
        assert len(result.placements) == 1
        assert result.placements[0].gemini_path == tmp_path / "GEMINI.md"
