"""Unit tests for ClaudeFormatter - CLAUDE.md generation."""

import shutil
import tempfile
from pathlib import Path

import pytest

from apm_cli.compilation.claude_formatter import (
    CLAUDE_HEADER,
    ClaudeCompilationResult,
    ClaudeFormatter,
    ClaudePlacement,
    format_claude_md,
)
from apm_cli.compilation.constants import BUILD_ID_PLACEHOLDER
from apm_cli.primitives.models import Chatmode, Instruction, PrimitiveCollection
from apm_cli.version import get_version


class TestClaudeFormatterInit:
    """Tests for ClaudeFormatter initialization."""

    def test_init_with_valid_directory(self, tmp_path):
        """Test initialization with a valid directory path."""
        formatter = ClaudeFormatter(str(tmp_path))
        assert formatter.base_dir == tmp_path
        assert formatter.warnings == []
        assert formatter.errors == []

    def test_init_with_current_directory(self):
        """Test initialization with default current directory."""
        formatter = ClaudeFormatter()
        assert formatter.base_dir.exists()

    def test_init_with_relative_path(self, tmp_path):
        """Test initialization with relative path."""
        formatter = ClaudeFormatter(".")
        assert formatter.base_dir.is_absolute()


class TestFormatDistributed:
    """Tests for format_distributed() method."""

    @pytest.fixture
    def temp_project(self):
        """Create a temporary project directory."""
        temp_dir = tempfile.mkdtemp()
        yield Path(temp_dir)
        shutil.rmtree(temp_dir, ignore_errors=True)

    @pytest.fixture
    def sample_primitives(self, temp_project):
        """Create sample primitives for testing."""
        primitives = PrimitiveCollection()

        # Add instructions
        instruction1 = Instruction(
            name="python-style",
            file_path=temp_project / ".github/instructions/python.instructions.md",
            description="Python coding standards",
            apply_to="**/*.py",
            content="Use type hints and follow PEP 8.",
            author="test",
            source="local",
        )

        instruction2 = Instruction(
            name="js-style",
            file_path=temp_project / ".github/instructions/js.instructions.md",
            description="JavaScript coding standards",
            apply_to="**/*.js",
            content="Use ES6+ features.",
            author="test",
            source="local",
        )

        primitives.add_primitive(instruction1)
        primitives.add_primitive(instruction2)

        return primitives

    def test_format_generates_header(self, temp_project, sample_primitives):
        """Test that CLAUDE.md contains correct header format."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        result = formatter.format_distributed(sample_primitives, placement_map)

        assert result.success
        assert len(result.content_map) == 1

        content = result.content_map[temp_project / "CLAUDE.md"]
        assert "# CLAUDE.md" in content
        assert CLAUDE_HEADER in content
        assert BUILD_ID_PLACEHOLDER in content
        assert f"<!-- APM Version: {get_version()} -->" in content

    def test_format_generates_footer(self, temp_project, sample_primitives):
        """Test that CLAUDE.md contains correct footer."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        result = formatter.format_distributed(sample_primitives, placement_map)

        content = result.content_map[temp_project / "CLAUDE.md"]
        assert "*This file was generated by APM CLI. Do not edit manually.*" in content
        assert "*To regenerate: `apm compile`*" in content

    def test_format_groups_by_apply_to_patterns(self, temp_project, sample_primitives):
        """Test that instructions are grouped by applyTo patterns."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        result = formatter.format_distributed(sample_primitives, placement_map)

        content = result.content_map[temp_project / "CLAUDE.md"]

        # Check pattern grouping
        assert "## Files matching `**/*.py`" in content
        assert "## Files matching `**/*.js`" in content
        assert "Use type hints and follow PEP 8." in content
        assert "Use ES6+ features." in content

    def test_format_includes_project_standards_section(self, temp_project, sample_primitives):
        """Test that Project Standards section is generated."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        result = formatter.format_distributed(sample_primitives, placement_map)

        content = result.content_map[temp_project / "CLAUDE.md"]
        assert "# Project Standards" in content

    def test_format_includes_source_attribution(self, temp_project, sample_primitives):
        """Test that source attribution comments are included."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        config = {"source_attribution": True}
        result = formatter.format_distributed(sample_primitives, placement_map, config)

        content = result.content_map[temp_project / "CLAUDE.md"]
        assert "<!-- Source:" in content

    def test_format_without_source_attribution(self, temp_project, sample_primitives):
        """Test that source attribution can be disabled."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        config = {"source_attribution": False}
        result = formatter.format_distributed(sample_primitives, placement_map, config)

        # Source attribution should not be tracked in placement
        for placement in result.placements:
            assert placement.source_attribution == {}

    def test_format_returns_compilation_stats(self, temp_project, sample_primitives):
        """Test that compilation statistics are returned."""
        formatter = ClaudeFormatter(str(temp_project))

        placement_map = {temp_project: list(sample_primitives.instructions)}
        result = formatter.format_distributed(sample_primitives, placement_map)

        assert result.stats["claude_files_generated"] == 1
        assert result.stats["total_instructions_placed"] == 2
        assert result.stats["total_patterns_covered"] == 2

    def test_format_empty_placement_map(self, temp_project):
        """Test formatting with empty placement map."""
        formatter = ClaudeFormatter(str(temp_project))
        primitives = PrimitiveCollection()

        result = formatter.format_distributed(primitives, {})

        assert result.success
        # No files should be generated without instructions or constitution
        assert len(result.content_map) == 0

    def test_format_with_constitution(self, temp_project):
        """Test formatting with constitution file."""
        # Create constitution file
        constitution_file = temp_project / "CONSTITUTION.md"
        constitution_file.write_text("# Constitution\n\nBe helpful and accurate.")

        formatter = ClaudeFormatter(str(temp_project))
        primitives = PrimitiveCollection()

        # Empty placement map but constitution exists
        result = formatter.format_distributed(primitives, {})

        assert result.success
        if result.content_map:
            content = list(result.content_map.values())[0]  # noqa: RUF015
            assert "# Constitution" in content
            assert "Be helpful and accurate." in content


class TestDependenciesImportSyntax:
    """Tests for @import syntax for dependencies."""

    @pytest.fixture
    def temp_project_with_deps(self):
        """Create a temporary project with apm_modules dependencies."""
        temp_dir = tempfile.mkdtemp()
        temp_path = Path(temp_dir).resolve()

        # Create apm_modules structure
        apm_modules = temp_path / "apm_modules"
        (apm_modules / "owner1" / "package1").mkdir(parents=True)
        (apm_modules / "owner2" / "package2").mkdir(parents=True)

        yield temp_path
        shutil.rmtree(temp_dir, ignore_errors=True)

    def test_dependencies_use_import_syntax(self, temp_project_with_deps):
        """Test that dependencies are listed with @import syntax."""
        formatter = ClaudeFormatter(str(temp_project_with_deps))
        primitives = PrimitiveCollection()

        instruction = Instruction(
            name="test",
            file_path=temp_project_with_deps / "test.instructions.md",
            description="Test",
            apply_to="**/*.py",
            content="Test content",
            author="test",
        )
        primitives.add_primitive(instruction)

        # Use resolved path for placement map key
        placement_map = {formatter.base_dir: [instruction]}
        result = formatter.format_distributed(primitives, placement_map)

        # Get content using the resolved path
        content = result.content_map[formatter.base_dir / "CLAUDE.md"]

        # Check @import syntax
        assert "@apm_modules/owner1/package1/CLAUDE.md" in content
        assert "@apm_modules/owner2/package2/CLAUDE.md" in content
        assert "# Dependencies" in content

    def test_dependencies_are_sorted(self, temp_project_with_deps):
        """Test that dependencies are sorted alphabetically."""
        formatter = ClaudeFormatter(str(temp_project_with_deps))
        deps = formatter._collect_dependencies()

        assert deps == sorted(deps)

    def test_no_dependencies_section_when_no_apm_modules(self, tmp_path):
        """Test that no Dependencies section when apm_modules doesn't exist."""
        formatter = ClaudeFormatter(str(tmp_path))
        deps = formatter._collect_dependencies()

        assert deps == []


class TestAgentsExcludedFromClaudeMd:
    """Tests verifying agents/workflows are NOT included in CLAUDE.md.

    Agents are handled separately via .github/agents/ files and .claude/skills/
    folders - they should NOT be embedded in CLAUDE.md (same as AGENTS.md).
    """

    @pytest.fixture
    def temp_project(self):
        """Create a temporary project directory."""
        temp_dir = tempfile.mkdtemp()
        yield Path(temp_dir).resolve()
        shutil.rmtree(temp_dir, ignore_errors=True)

    def test_agents_not_in_claude_md(self, temp_project):
        """Test that agents/chatmodes are NOT included in CLAUDE.md."""
        formatter = ClaudeFormatter(str(temp_project))
        primitives = PrimitiveCollection()

        chatmode = Chatmode(
            name="code-reviewer",
            file_path=temp_project / ".github/chatmodes/code-reviewer.chatmode.md",
            description="Expert code reviewer",
            apply_to=None,
            content="You are an expert code reviewer. Focus on security and performance.",
            author="test",
        )
        primitives.add_primitive(chatmode)

        instruction = Instruction(
            name="test",
            file_path=temp_project / "test.instructions.md",
            description="Test",
            apply_to="**/*.py",
            content="Test content",
            author="test",
        )
        primitives.add_primitive(instruction)

        # Use the formatter's resolved base_dir as the key
        placement_map = {formatter.base_dir: [instruction]}
        result = formatter.format_distributed(primitives, placement_map)

        content = result.content_map[formatter.base_dir / "CLAUDE.md"]

        # Workflows section should NOT exist - agents go to .github/agents/
        assert "# Workflows" not in content
        assert "## code-reviewer" not in content
        # Instructions should still be there
        assert "Test content" in content

    def test_claude_md_only_contains_instructions(self, temp_project):
        """Test that CLAUDE.md only contains instructions, not agents."""
        formatter = ClaudeFormatter(str(temp_project))
        primitives = PrimitiveCollection()

        chatmode = Chatmode(
            name="reviewer",
            file_path=temp_project / "reviewer.chatmode.md",
            description="Reviewer",
            apply_to=None,
            content="You are a reviewer.",
            author="test",
        )
        primitives.add_primitive(chatmode)

        instruction = Instruction(
            name="python-standards",
            file_path=temp_project / "python.instructions.md",
            description="Python standards",
            apply_to="**/*.py",
            content="Use type hints for all functions.",
            author="test",
        )
        primitives.add_primitive(instruction)

        placement_map = {formatter.base_dir: [instruction]}
        result = formatter.format_distributed(primitives, placement_map)

        content = result.content_map[formatter.base_dir / "CLAUDE.md"]

        # Should have instructions
        assert "Use type hints for all functions." in content
        assert "**/*.py" in content

        # Should NOT have agent content
        assert "You are a reviewer." not in content
        assert "Workflows" not in content

    def test_multiple_chatmodes_excluded(self, temp_project):
        """Test that multiple chatmodes are all excluded from CLAUDE.md."""
        formatter = ClaudeFormatter(str(temp_project))
        primitives = PrimitiveCollection()

        chatmode1 = Chatmode(
            name="reviewer",
            file_path=temp_project / "reviewer.chatmode.md",
            description="Code reviewer",
            apply_to=None,
            content="Review code.",
            author="test",
        )
        chatmode2 = Chatmode(
            name="architect",
            file_path=temp_project / "architect.chatmode.md",
            description="System architect",
            apply_to=None,
            content="Design systems.",
            author="test",
        )
        primitives.add_primitive(chatmode1)
        primitives.add_primitive(chatmode2)

        instruction = Instruction(
            name="test",
            file_path=temp_project / "test.instructions.md",
            description="Test",
            apply_to="**/*.py",
            content="Test instruction content",
            author="test",
        )
        primitives.add_primitive(instruction)

        placement_map = {formatter.base_dir: [instruction]}
        result = formatter.format_distributed(primitives, placement_map)

        content = result.content_map[formatter.base_dir / "CLAUDE.md"]

        # Agents should NOT be in CLAUDE.md
        assert "## reviewer" not in content
        assert "## architect" not in content
        assert "Review code." not in content
        assert "Design systems." not in content

        # But instructions should be there
        assert "Test instruction content" in content


class TestConvenienceFunctions:
    """Tests for module-level convenience functions."""

    @pytest.fixture
    def temp_project(self):
        """Create a temporary project directory."""
        temp_dir = tempfile.mkdtemp()
        yield Path(temp_dir)
        shutil.rmtree(temp_dir, ignore_errors=True)

    def test_format_claude_md_function(self, temp_project):
        """Test the format_claude_md convenience function."""
        primitives = PrimitiveCollection()

        instruction = Instruction(
            name="test",
            file_path=temp_project / "test.instructions.md",
            description="Test",
            apply_to="**/*.py",
            content="Test content",
            author="test",
        )
        primitives.add_primitive(instruction)

        placement_map = {temp_project: [instruction]}

        result = format_claude_md(primitives, placement_map, str(temp_project))

        assert result.success
        assert len(result.content_map) == 1


class TestDataclasses:
    """Tests for dataclass structures."""

    def test_claude_placement_defaults(self):
        """Test ClaudePlacement default values."""
        placement = ClaudePlacement(claude_path=Path("test/CLAUDE.md"), instructions=[])

        assert placement.agents == []
        assert placement.dependencies == []
        assert placement.coverage_patterns == set()
        assert placement.source_attribution == {}

    def test_claude_compilation_result_defaults(self):
        """Test ClaudeCompilationResult default values."""
        result = ClaudeCompilationResult(success=True, placements=[], content_map={})

        assert result.warnings == []
        assert result.errors == []
        assert result.stats == {}


class TestErrorHandling:
    """Tests for error handling in ClaudeFormatter."""

    @pytest.fixture
    def temp_project(self):
        """Create a temporary project directory."""
        temp_dir = tempfile.mkdtemp()
        yield Path(temp_dir)
        shutil.rmtree(temp_dir, ignore_errors=True)

    def test_format_distributed_handles_exceptions(self, temp_project):
        """Test that format_distributed handles exceptions gracefully."""
        formatter = ClaudeFormatter(str(temp_project))

        primitives = PrimitiveCollection()

        instruction = Instruction(
            name="test",
            file_path=temp_project / "test.md",
            description="Test",
            apply_to="**/*.py",
            content="Test",
            author="test",
        )
        primitives.add_primitive(instruction)

        result = formatter.format_distributed(primitives, {temp_project: [instruction]})

        assert isinstance(result, ClaudeCompilationResult)
